### ISSUE TITLE
Leyenda

### ISSUE THREAD

**Issue by stopy90** [1N0T/calendarHeatmap#1]
Buenas,

Genial el código , muy útil

¿Habría alguna forma de añadir una leyenda?

¿Sería posible discretizar los valores para ver los colores en un rango? Por ejemplo 0-2 , 2-5 , 5-10 ,> 10

Un saludo

**Comment by 1N0T** [comment]
Hola,

me alegra que encuentres útil el código (siempre tienes la opción de darle una estrella para facilitar que otros usuarios le presten atención).

Sin modificar el código, para representar categorías, en lugar de valores contínuos, sería suficiente con realizar la modificación previa de la lista de valores. Por ejemplo, en lugar de 2,3,6,7,15 podrías pasar 0,0,5,5,15 para representar rangos de 5 en 5 (ó 0,0,1,1,3).

Si además, quieres colores discretos, en lugar de un degradado contínuo, utiliza una de las paletas discretas de matplotlib, como **Piared** (https://matplotlib.org/2.0.2/_images/colormaps_reference_04.png).

Si quieres un mayor control, podrías pasar por parámetro un mapa de colores personalizado, pero creo que añade complejidad al uso de la función.

En cuanto a la leyenda, me imagino que te refieres a mostrar una escala de colores y el valor numérico que representa. Me lo estuve planteando, pero como el número de meses y la cantidad de filas y columnas es variable, resultaba difícil mostrar una disposición que resultara siempre estéticamente atractiva (te queda el recurso de pasar el parámetro **mostrar_valores=True** que visualiza el valor concreto).

**Comment by stopy90** [comment]
Muchas gracias por la respuesta!

**Comment by 1N0T** [comment]
En la versión v1.0.1 he añadido la posibilidad de personalizar rango de la escala de valores y visualización del mapa de colores correspondiente.
